In [1]:
import numpy as np
#import numpy and name as np 
#np is use in  industruial level so it is prefered to use np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])
#one d array

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
type(arr)

numpy.ndarray

In [9]:
arr = np.array([[1,2,3,4],[1,3,6,8]])
#2d array

In [10]:
arr


array([[1, 2, 3, 4],
       [1, 3, 6, 8]])

In [11]:
arr.T
#change row in columns

array([[1, 1],
       [2, 3],
       [3, 6],
       [4, 8]])

In [13]:
arr.max()
#max of array

8

In [14]:
arr.min()
#min of array

1

In [15]:
arr.mean()
#min of array

3.5

In [17]:
arr.shape
#shape of array 
#the shape of an array is the no of element in each deminsion

(2, 4)

In [18]:
arr[1:3]
#slicing of array

array([[1, 3, 6, 8]])

In [19]:
arr[1:2]

array([[1, 3, 6, 8]])

In [20]:
arr[1:1]

array([], shape=(0, 4), dtype=int32)

In [21]:
a  = np.array([1,2,3,4,5,6,7,8])

In [22]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
a[1:6]

array([2, 3, 4, 5, 6])

In [24]:
a[3:]

array([4, 5, 6, 7, 8])

In [25]:
a[:5]

array([1, 2, 3, 4, 5])

In [26]:
a[1:5:2]
#sliceing of 2d array

array([2, 4])

In [27]:
a[1:5:2:3]

SyntaxError: invalid syntax (3367081539.py, line 1)

In [28]:
a[::2]

array([1, 3, 5, 7])

In [29]:
a[2::]

array([3, 4, 5, 6, 7, 8])

In [30]:
a[1::]

array([2, 3, 4, 5, 6, 7, 8])

In [31]:
b = np.array([[1,2,3,4,5],[6,5,4,3,2]])

In [32]:
b

array([[1, 2, 3, 4, 5],
       [6, 5, 4, 3, 2]])

In [35]:
b[1,1:4]

array([5, 4, 3])

In [34]:
b[1,1:2]

array([5])

In [37]:
b[0:3,2:5]

array([[3, 4, 5],
       [4, 3, 2]])

In [38]:
#copy and view in m=numpy
#copy of orignal data into another array will not affect the original data
c = np.array([2,5,34,23,23])
x = c.copy()
x


array([ 2,  5, 34, 23, 23])

In [39]:
x[2] = 65

In [40]:
x

array([ 2,  5, 65, 23, 23])

In [49]:
#make a view and change original data
y =  x.view()
x[0]=42
x

array([42,  5, 65, 23, 23])

In [50]:
#make a view and change original data
#this will change both the orignal and view
y =  x.view()
x[0]=42
y

array([42,  5, 65, 23, 23])

In [51]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
np.where(a>4)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))